install.packages("polycor",dep=TRUE)
library(polycor)
df <- read.csv("r-csv/内容理解と楽しさ.csv",header=T,fileEncoding="CP932")
df1 <- read.csv("r-csv/相関分析.csv",header=T,fileEncoding="CP932")
df
df1
row1_1<-df1[,colnames(df1)=="通訳回数"]
row1_2<-df1[,colnames(df1)=="通訳の楽しさ"]
row1_3<-df1[,colnames(df1)=="通訳品質"]
row1_4<-df1[,colnames(df1)=="手話分かりやすさ"]
row1_5<-df1[,colnames(df1)=="内容理解"]
row1_6<-df1[,colnames(df1)=="再生倍率1.5倍速はどう感じたか"]
polyserial(row1_3,row1_4)
polyserial(row1_3,row1_5)
polyserial(row1_3,row1_6)
row1<-df[,colnames(df)=="内容理解"]
row2<-df[,colnames(df)=="通訳の楽しさ"]
row3<-df[,colnames(df)=="手話分かりやすさ"]
row4<-df[,colnames(df)=="早送りについてどう感じた"]
row5<-df[,colnames(df)=="通訳時間"]
row6<-df[,colnames(df)=="通訳品質"]
polychor(row1,row2)
cor.test(row1,row2)
cor.test(row1,row2,method="spearman")
cor.test(row1,row2,method="kendall")
cor.test(row1,row4)
cor.test(row1,row4,method="spearman")
cor.test(row1,row4,method="kendall")
polychor(row1,row2,ML=TRUE)
polychor(row2,row3)
polychor(row2,row3,ML=TRUE)
polychor(row1,row3)
polychor(row1,row3,ML=TRUE)
polychor(row3,row4)
polychor(row3,row4,ML=TRUE)
polychor(row1,row4)
polychor(row1,row4,ML=TRUE)
polychor(row2,row4)
polychor(row2,row4,ML=TRUE)
cor.test(row5,row6)

